# -*- coding: utf-8 -*-
#
# grooved documentation build configuration file, created by
# sphinx-quickstart on Sun Mar 22 14:43:38 2015.
#
# This file is execfile()d with the current directory set to its
# containing dir.
#
# Note that not all possible configuration values are present in this
# autogenerated file.
#
# All configuration values have a default; values that are commented out
# serve to show the default.

import sys
import os

# If extensions (or modules to document with autodoc) are in ano